#!/bin/bash
# Change your_token and your_appid with yours.

ACCESS_TOKEN=your_token
CATAPUSH_MESSENGER_APPID=your_appid
EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo 'Syntax error: catamessenger internationalcodedestinationnumber "text to send"'
  echo 'For example: catamessenger 393331234567 "help me"'
  exit $E_BADARGS
fi

# Debug
# echo 'Sending text "'$2'" to '$1'...'
# echo 'APPID='$CATAPUSH_MESSENGER_APPID' - ACCESS TOKEN='$ACCESS_TOKEN'  '

curl --silent --request POST \
  --url https://api.catapush.com/1/messages \
  --header 'accept: application/json' \
  --header 'authorization: Bearer '$ACCESS_TOKEN'' \
  --header 'content-type: application/json' \
  --data '{"mobileAppId":'$CATAPUSH_MESSENGER_APPID',"text":"'"$2"'","recipients":[{"identifier":"'$1'"}]}' > /dev/null
